updated travis for ants

diff --git a/neuroconductor_travis_ants.yml b/neuroconductor_travis_ants.yml
--- a/neuroconductor_travis_ants.yml
+++ b/neuroconductor_travis_ants.yml
@@ -26,6 +26,7 @@ before_install:
   - cat ${fname}; source ${fname}; rm ${fname}  
   - cat DESCRIPTION
   - export PACKAGE_NAME=`package_name`  
+  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
   - Rscript -e 'source("https://install-github.me/mangothecat/callr")'
   - remove_neuroc_packages
   - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
@@ -54,18 +55,29 @@ before_install:
       install_missing_remote_deps ${ants_user}/ANTsR ;
       gh_binary_install ${ants_user}/ANTsR ;
     fi    
+  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; 
+    then 
+      export _R_CHECK_FORCE_SUGGESTS_=0 ;
+    fi
   - cat DESCRIPTION
   - install_remotes_no_dep
   - cat DESCRIPTION
   - echo $PATH ;
+  - install_deps_no_suggests
 
 script:
   # - source ~/.R/Makevars
   - x=`export_clang_cxx`; eval ${x}
   - travis_wait 100 R CMD build ${R_BUILD_ARGS} . 
+  - rm -f travis_wait*.log
   - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
   - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+  - rm -f travis_wait*.log
+  - check_fail
+  - check_warnings
+  # - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))" ;
+  # - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log" ; if [[ $? -eq 0 ]]; error 1; fi  
   # - if [[ ${#TRAVIS_TAG} -eq 0 ]]; 
   #   then 
   #   travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; 
@@ -96,5 +108,7 @@ deploy:
   on:
     tags: true
 
-# after_deploy:
-#   - travis_wait 100 Rscript -e 'covr::coveralls(type = "all")'
+after_deploy:
+  - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" ]]; 
+      Rscript -e 'covr::coveralls(type = "all")' ;
+    fi 
