updated

diff --git a/neuroconductor_travis_ants.yml b/neuroconductor_travis_ants.yml
--- a/neuroconductor_travis_ants.yml
+++ b/neuroconductor_travis_ants.yml
@@ -10,17 +10,17 @@ addons:
   apt:
     packages:
     - libcurl4-openssl-dev
-    - libxml2-dev       
+    - libxml2-dev
     - libfftw3-dev
     - libgsl0-dev
-    - mesa-common-dev 
-    - libglu1-mesa-dev 
+    - mesa-common-dev
+    - libglu1-mesa-dev
     - devscripts
-    
+
 os:
   - linux
   - osx
-osx_image: xcode9.4 
+osx_image: xcode9.4
 
 # r_binary_packages:
 #   - rgl
@@ -44,7 +44,7 @@ env:
   - R_BUILD_ARGS="--no-manual"
   - R_CHECK_ARGS="--as-cran --install-args=--build"
   - RGL_USE_NULL=TRUE
-  - WARNINGS_ARE_ERRORS=1 
+  - WARNINGS_ARE_ERRORS=1
   - PROJECT_NAME=neuroconductor
   - DISPLAY=:99.0
   - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
@@ -52,22 +52,22 @@ env:
   - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
 
 before_install:
-  - if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi  
-  - ulimit -n 2048  
+  - if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi
+  - ulimit -n 2048
   - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
   - export PROJ_DIR=`basename $PWD`
   - echo "travis_wait*\.log$" >> .Rbuildignore
   - fname=travis_helpers.sh
   - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}  
+  - cat ${fname}; source ${fname}; rm ${fname}
   - cat DESCRIPTION
   - start_xvfb ;
-  - jags_install || true;  
+  - jags_install || true;
   - if `need_v8`; then v8_install || true; fi
-  - dcmtk_install || true;    
+  - dcmtk_install || true;
   - gsl_install 2.1 || true ; # now checking version
   - export rver=`r_version`; echo $rver ;
-  - export PACKAGE_NAME=`package_name`  
+  - export PACKAGE_NAME=`package_name`
   - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
   - remove_neuroc_packages
   - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
@@ -75,46 +75,46 @@ before_install:
   - x=`export_clang_cxx`; eval ${x}
   - if [ "$TRAVIS_OS_NAME" = "osx" ];
     then
-      no_open_mp ; 
-      brew install -v freetype ;      
+      no_open_mp ;
+      brew install -v freetype ;
     fi
   - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
-  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
-  - clang_cxx  
+  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+  - clang_cxx
   - export cmake_version="3.11"
   - cmake --version
   - x=`cmake_setup`; echo "${x}"; eval ${x};
   - cmake --version
   - export ants_user=neuroconductor
-  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}" == "ANTsR" ]];   
+  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}" == "ANTsR" ]];
     then
       Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repo = 'http://cran.rstudio.com')" ;
     fi
-  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]];   
+  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" ]];
     then
       export R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ;
       export R_CHECK_ARGS="--no-vignettes ${R_CHECK_ARGS}" ;
-    fi    
-  - if [[ "${PACKAGE_NAME}" != "ITKR" ]]; 
+    fi
+  - if [[ "${PACKAGE_NAME}" != "ITKR" ]];
     then
       echo "Installing Missing Deps ITKR" ;
       install_missing_remote_deps_all ${ants_user}/ITKR ;
-      gh_binary_install ${ants_user}/ITKR ;    
+      gh_binary_install ${ants_user}/ITKR ;
     fi
-  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]]; 
+  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]];
     then
       echo "Installing Missing Deps ANTsRCore" ;
       install_missing_remote_deps_all ${ants_user}/ANTsRCore;
       gh_binary_install_passive ${ants_user}/ANTsRCore ;
     fi
-  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsR" ]]; 
+  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsR" ]];
     then
       echo "Installing Missing Deps ANTsR" ;
       install_missing_remote_deps_all ${ants_user}/ANTsR ;
       gh_binary_install_passive ${ants_user}/ANTsR ;
-    fi    
-  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]]; 
-    then 
+    fi
+  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]];
+    then
       export _R_CHECK_FORCE_SUGGESTS_=false ;
     fi
   - cat DESCRIPTION
@@ -122,15 +122,15 @@ before_install:
   - cat DESCRIPTION
   - echo $PATH ;
   - install_deps_no_suggests
-  - setup_python 3.6 false ;  
-  - install_python_requirements ; 
-  - R CMD javareconf ;   
-  - travis_run_cache 
+  - setup_python 3.6 false ;
+  - install_python_requirements ;
+  - R CMD javareconf ;
+  - travis_run_cache
 
 script:
   # - source ~/.R/Makevars
   - x=`export_clang_cxx`; eval ${x}
-  - travis_wait 100 R CMD build ${R_BUILD_ARGS} . 
+  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
   - rm -f travis_wait*.log
   - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
@@ -138,17 +138,17 @@ script:
   - rm -f travis_wait*.log
   - if [[ $CHECK_RET -ne 0 ]];
     then
-      echo "R CMD check failed"; 
-      check_fail; 
-      dump_logs; 
+      echo "R CMD check failed";
+      check_fail;
+      dump_logs;
       travis_terminate 1;
-    fi  
+    fi
   - check_warnings
   # - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))" ;
-  # - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log" ; if [[ $? -eq 0 ]]; error 1; fi  
-  # - if [[ ${#TRAVIS_TAG} -eq 0 ]]; 
-  #   then 
-  #   travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; 
+  # - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log" ; if [[ $? -eq 0 ]]; error 1; fi
+  # - if [[ ${#TRAVIS_TAG} -eq 0 ]];
+  #   then
+  #   travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}";
   #   fi
 
 after_success:
@@ -160,19 +160,19 @@ after_failure:
 # so no overwrite of linux build
 before_deploy:
   - if [ "$TRAVIS_OS_NAME" = "osx" ];
-    then 
-      PKG_TARBALL=$(ls -1t *.tgz | head -n 1); 
+    then
+      PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
       PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
       mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
-      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;      
-    fi   
+      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
+    fi
   - if [ "$TRAVIS_OS_NAME" = "linux" ];
-    then 
-      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1); 
+    then
+      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1);
       PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
       mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
       echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
-    fi    
+    fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ];
     then
       rm -f *.tar.gz;
@@ -181,22 +181,21 @@ before_deploy:
 deploy:
   provider: releases
   skip_cleanup: true
-  token:
-    secure: "${NEUROCKEY}"
+  token: $GITHUB_TOKEN
   file_glob: true
-  overwrite: true   
+  overwrite: true
   file: ${PACKAGE_NAME}*.t*gz
   'on':
     tags: true
 
 after_deploy:
-  - echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false"; else run_coverage=; fi; 
+  - echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false"; else run_coverage=; fi;
   - if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then
       echo 'covr::coveralls(type = "all", quiet = FALSE)' > neuroc_covr.R ;
       travis_wait 100 Rscript neuroc_covr.R ;
       rm neuroc_covr.R ;
     fi
-  # - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" && -z "${run_coverage}" ]]; 
+  # - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" && -z "${run_coverage}" ]];
   #   then
   #     if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then
   #       Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ;
