updated Osler yml files

diff --git a/oslerinhealth_appveyor_ants.yml b/oslerinhealth_appveyor_ants.yml
--- a/oslerinhealth_appveyor_ants.yml
+++ b/oslerinhealth_appveyor_ants.yml
@@ -1,104 +1,172 @@
-# OslerInHealth Template
-# DO NOT CHANGE the "init" and "install" sections below
+# OslerInHealth Template for ANTsR Dep
+language: r
+sudo: false
+cache: packages
+warnings_are_errors: true
+use_bioc: true
+bioc_required: true
+cran: http://cran.rstudio.com
+dist: trusty
 
-# Download script file from GitHub
-init:
-  ps: |
-        $ErrorActionPreference = "Stop"
-        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
-        Import-Module '..\appveyor-tool.ps1'
+addons:
+  apt:
+    packages:
+    - libfftw3-dev
+    - libgsl0-dev
+    - libgsl0ldbl
 
-environment:
+os:
+  - linux
+  - osx
+osx_image: xcode9
+
+
+r:
+- 3.2
+- 3.3
+- 3.4
+- release
+- devel
+
+matrix:
+  allow_failures:
+    - r: devel
+
+env:
   global:
-    USE_RTOOLS: true
-    R_CHECK_INSTALL_ARGS: "--install-args=--build --no-multiarch "
-    WARNINGS_ARE_ERRORS: 1
+  - R_BUILD_ARGS="--no-manual"
+  - R_CHECK_ARGS="--as-cran --install-args=--build"
+  - RGL_USE_NULL=TRUE
+  - WARNINGS_ARE_ERRORS=1
+  - PROJECT_NAME=oslerinhealth
+  - DISPLAY=:99.0
 
-install:
-  - ps: Bootstrap
+before_install:
+  - ulimit -n 2048
+  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
+  - export PROJ_DIR=`basename $PWD`
+  - echo "travis_wait*\.log$" >> .Rbuildignore
+  - fname=travis_helpers.sh
+  - wget -O ${fname} http://bit.ly/travis_helpers
+  - cat ${fname}; source ${fname}; rm ${fname}
+  - cat DESCRIPTION
+  - start_xvfb ;
+  - export rver=`r_version`; echo $rver ;
+  - export PACKAGE_NAME=`package_name`
+  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
+  - remove_neuroc_packages
+  - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
+  # does all the clang exports
+  - x=`export_clang_cxx`; eval ${x}
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      no_open_mp ;
+    fi
+  - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
+  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+  - clang_cxx
+  - export cmake_version="3.11"
+  - cmake --version
+  - x=`cmake_setup`; echo "${x}"; eval ${x};
+  - cmake --version
+  - export ants_user=oslerinhealth
+  - echo "Installing Missing Deps ITKR"
+  - install_missing_remote_deps ${ants_user}/ITKR
+  - gh_binary_install ${ants_user}/ITKR ;
+  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}" == "ANTsR" ]];
+    then
+      export R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ;
+    fi
+  - if [[ "${PACKAGE_NAME}" != "ITKR" ]];
+    then
+      echo "Installing Missing Deps ANTsRCore" ;
+      install_missing_remote_deps ${ants_user}/ANTsRCore;
+      gh_binary_install_passive ${ants_user}/ANTsRCore ;
+    fi
+  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]];
+    then
+      echo "Installing Missing Deps ANTsR" ;
+      install_missing_remote_deps ${ants_user}/ANTsR ;
+      gh_binary_install_passive ${ants_user}/ANTsR ;
+    fi
+  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]];
+    then
+      export _R_CHECK_FORCE_SUGGESTS_=0 ;
+    fi
+  - cat DESCRIPTION
+  - install_remotes_no_dep
+  - cat DESCRIPTION
+  - echo $PATH ;
+  - install_deps_no_suggests
+  - install_python_requirements ;
+  - travis_run_cache
 
-cache:
-  - C:\RLibrary
-
-# Adapt as necessary starting from here
-build_script:
-  - mkdir -p C:\rtm
-  - set TMP=C:/rtm
-  - set TEMP=C:/rtm
-  - set TMPDIR=C:/rtm  
-  # need to move to higher dir because CMake path req
-  - mkdir C:\run
-  - cp -avr * C:\run
-  # need the tool a level above
-  - cp ../travis-tool.sh C:\
-  - cd C:\run
-  # - ps: Invoke-WebRequest http://ci.appveyor.com/api/buildjobs/tu3s6m73682lhvc1/artifacts/ITKR_0.4.12.3.zip -OutFile ".\ITKR.zip"
-  - ps: Invoke-WebRequest https://github.com/muschellij2/ITKR/releases/download/v0.4.12.2/ITKR_0.4.12.2.zip -OutFile ".\ITKR.zip"
+script:
+  # - source ~/.R/Makevars
+  - x=`export_clang_cxx`; eval ${x}
+  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+  - rm -f travis_wait*.log
+  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
-  - Rscript -e "install.packages('ITKR.zip', repos = NULL)"  
-  - rm ITKR.zip
-  # - ps: Invoke-WebRequest https://github.com/muschellij2/ANTsRCore/releases/download/v0.4.12.2/ITKR_0.4.12.2.zip -OutFile ".\ITKR.zip"
-  # - ls
-  # - Rscript -e "install.packages('ANTsRCore.zip', repos = NULL)"  
-  # - rm ANTsRCore.zip  
-  # - ps: Invoke-WebRequest https://github.com/muschellij2/ANTsRCore/releases/download/v0.4.12.2/ITKR_0.4.12.2.zip -OutFile ".\ITKR.zip"
-  # - ls
-  # - Rscript -e "install.packages('ANTsR.zip', repos = NULL)"  
-  # - rm ANTsR.zip  
-  # setting PATH to be specific - no MinGW overall - just R's
-  - set PATH=C:\Rtools\bin;C:\Rtools\MinGW\bin;
-  - set PATH=%PATH%;C:\Rtools\mingw_64\bin;
-  - set PATH=%PATH%;C:\Program Files\Git\cmd;
-  - set PATH=%PATH%;"C:\Program Files (x86)\CMake\bin";
-  - set PATH=%PATH%;C:\R\bin\i386;  
-  - set PATH=%PATH%;C:\Program Files\Git\usr\bin  
-  - set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\npm
-  - set PATH=%PATH%;C:\Users\appveyor\AppData\Local\Yarn\bin
-  - set PATH=%PATH%;C:\Program Files\AppVeyor\BuildAgent\
-  - set PATH=%PATH%;C:\Windows\system32
-  - set PATH=%PATH%;C:\Windows
-  - set PATH=%PATH%;C:\Windows\System32\Wbem
-  - set PATH=%PATH%;C:\Windows\System32\WindowsPowerShell\v1.0\
-  - set PATH=%PATH%;C:\Program Files\7-Zip
-  - travis-tool.sh install_deps
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+  - rm -f travis_wait*.log
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed";
+      check_fail;
+      dump_logs;
+      travis_terminate 1;
+    fi
+  - check_warnings
+  # - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))" ;
+  # - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log" ; if [[ $? -eq 0 ]]; error 1; fi
+  # - if [[ ${#TRAVIS_TAG} -eq 0 ]];
+  #   then
+  #   travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}";
+  #   fi
 
-test_script:
-  - travis-tool.sh run_tests
-  - ls
-  - cp -r C:/run/* %APPVEYOR_BUILD_FOLDER%
-  - cd %APPVEYOR_BUILD_FOLDER%
-  - ls
+after_success:
+  - dump_logs
 
+after_failure:
+  - dump_logs
 
-on_failure:
-  - 7z a failure.zip *.Rcheck\*
-  - appveyor PushArtifact failure.zip
-
-artifacts:
-  - path: '*.Rcheck\**\*.log'
-    name: Logs
-
-  - path: '*.Rcheck\**\*.zip'
-    name: Bits    
-
-  - path: '*.Rcheck\**\*.out'
-    name: Logs
-
-  - path: '*.Rcheck\**\*.fail'
-    name: Logs
-
-  - path: '*.Rcheck\**\*.Rout'
-    name: Logs
-
-  - path: '\*_*.zip'
-    name: Bits
+# so no overwrite of linux build
+before_deploy:
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
+      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
+      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
+      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
+    fi
+  - if [ "$TRAVIS_OS_NAME" = "linux" ];
+    then
+      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1);
+      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
+      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
+      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
+    fi
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      rm -f *.tar.gz;
+    fi
 
 deploy:
-  provider: GitHub
-  description: 'Windows Binary'
-  auth_token:
-    secure: ${NEUROCKEY}
-  draft: false
-  prerelease: false
+  provider: releases
+  skip_cleanup: true
+  api_key:
+    secure: "${NEUROCKEY}"
+  file_glob: true
+  file: ${PACKAGE_NAME}*.t*gz
   on:
-    appveyor_repo_tag: true
+    tags: true
+
+after_deploy:
+  - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" ]];
+    then
+      if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then
+        Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ;
+      fi
+    fi
+
diff --git a/oslerinhealth_travis_ants.yml b/oslerinhealth_travis_ants.yml
--- a/oslerinhealth_travis_ants.yml
+++ b/oslerinhealth_travis_ants.yml
@@ -1,4 +1,4 @@
-# OslerInHealth Template
+# OslerInHealth Template for ANTsR Dep
 language: r
 sudo: false
 cache: packages
@@ -6,71 +6,147 @@ warnings_are_errors: true
 use_bioc: true
 bioc_required: true
 cran: http://cran.rstudio.com
-dist: precise
+dist: trusty
+
+addons:
+  apt:
+    packages:
+    - libfftw3-dev
+    - libgsl0-dev
+    - libgsl0ldbl
 
 os:
   - linux
   - osx
+osx_image: xcode9
+
+
+r:
+- 3.2
+- 3.3
+- 3.4
+- release
+- devel
+
+matrix:
+  allow_failures:
+    - r: devel
 
 env:
   global:
-  - R_BUILD_ARGS="--no-build-vignettes --no-manual"
+  - R_BUILD_ARGS="--no-manual"
   - R_CHECK_ARGS="--as-cran --install-args=--build"
   - RGL_USE_NULL=TRUE
+  - WARNINGS_ARE_ERRORS=1
   - PROJECT_NAME=oslerinhealth
+  - DISPLAY=:99.0
 
 before_install:
-  - export PROJ_DIR=`basename $PWD`    
+  - ulimit -n 2048
+  - export LD_LIBRARY_PATH=/usr/local/clang/lib:${LD_LIBRARY_PATH}
+  - export PROJ_DIR=`basename $PWD`
+  - echo "travis_wait*\.log$" >> .Rbuildignore
   - fname=travis_helpers.sh
   - wget -O ${fname} http://bit.ly/travis_helpers
-  - cat ${fname}; source ${fname}; rm ${fname}  
+  - cat ${fname}; source ${fname}; rm ${fname}
   - cat DESCRIPTION
-  - jags_install  
+  - start_xvfb ;
+  - export rver=`r_version`; echo $rver ;
+  - export PACKAGE_NAME=`package_name`
+  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
   - remove_neuroc_packages
   - export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=1
   # does all the clang exports
   - x=`export_clang_cxx`; eval ${x}
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      no_open_mp ;
+    fi
   - echo "CC=${CC}, CXX=${CXX}, CXX1X=${CXX1X}"
-  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"  
-  - clang_cxx  
-  - export cmake_version="3.4"
+  - echo "CXX1XSTD=${CXX1XSTD}, CXX11=${CXX11}"
+  - clang_cxx
+  - export cmake_version="3.11"
   - cmake --version
   - x=`cmake_setup`; echo "${x}"; eval ${x};
   - cmake --version
-  - export ants_user=neuroconductor
-  - install_missing_remote_deps ${ants_user}/ITKR ${ants_user}/ANTsRCore ${ants_user}/ANTsR
-  - echo "Done Installing Missing Deps"
-  - gh_binary_install ${ants_user}/ITKR
-  - gh_binary_install ${ants_user}/ANTsRCore
-  - gh_binary_install ${ants_user}/ANTsR
+  - export ants_user=oslerinhealth
+  - echo "Installing Missing Deps ITKR"
+  - install_missing_remote_deps ${ants_user}/ITKR
+  - gh_binary_install ${ants_user}/ITKR ;
+  - if [[ "${PACKAGE_NAME}" == "ITKR" || "${PACKAGE_NAME}" == "ANTsRCore" || "${PACKAGE_NAME}" == "ANTsR" ]];
+    then
+      export R_BUILD_ARGS="${R_BUILD_ARGS} --no-build-vignettes " ;
+    fi
+  - if [[ "${PACKAGE_NAME}" != "ITKR" ]];
+    then
+      echo "Installing Missing Deps ANTsRCore" ;
+      install_missing_remote_deps ${ants_user}/ANTsRCore;
+      gh_binary_install_passive ${ants_user}/ANTsRCore ;
+    fi
+  - if [[ "${PACKAGE_NAME}" != "ANTsRCore" && "${PACKAGE_NAME}" != "ITKR" ]];
+    then
+      echo "Installing Missing Deps ANTsR" ;
+      install_missing_remote_deps ${ants_user}/ANTsR ;
+      gh_binary_install_passive ${ants_user}/ANTsR ;
+    fi
+  - if [[ "${PACKAGE_NAME}" == "ANTsR" ]];
+    then
+      export _R_CHECK_FORCE_SUGGESTS_=0 ;
+    fi
   - cat DESCRIPTION
   - install_remotes_no_dep
   - cat DESCRIPTION
-  - export PACKAGE_NAME=`package_name`
   - echo $PATH ;
+  - install_deps_no_suggests
+  - install_python_requirements ;
+  - travis_run_cache
 
 script:
   # - source ~/.R/Makevars
   - x=`export_clang_cxx`; eval ${x}
-  - cd ..
-  - travis_wait 100 R CMD build ${PROJ_DIR} ${R_BUILD_ARGS}
-  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
+  - travis_wait 100 R CMD build ${R_BUILD_ARGS} .
+  - rm -f travis_wait*.log
+  - PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1)
   - ls
-  - if [[ ${#TRAVIS_TAG} -eq 0 ]]; 
-    then 
-    travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_FILE_NAME}"; 
+  - travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}"; CHECK_RET=$? ;
+  - rm -f travis_wait*.log
+  - if [[ $CHECK_RET -ne 0 ]];
+    then
+      echo "R CMD check failed";
+      check_fail;
+      dump_logs;
+      travis_terminate 1;
     fi
-
-after_failure:
-  - cat ${PACKAGE_NAME}.Rcheck/00install.out
-  - cat ${PACKAGE_NAME}.Rcheck/00check.log
+  - check_warnings
+  # - Rscript -e "message(devtools::check_failures(path = \"${RCHECK_DIR}\"))" ;
+  # - grep -q -R "WARNING" "${RCHECK_DIR}/00check.log" ; if [[ $? -eq 0 ]]; error 1; fi
+  # - if [[ ${#TRAVIS_TAG} -eq 0 ]];
+  #   then
+  #   travis_wait 100 R CMD check ${R_CHECK_ARGS} "${PKG_TARBALL}";
+  #   fi
 
 after_success:
-  - cat ${PACKAGE_NAME}.Rcheck/00install.out
-  - cat ${PACKAGE_NAME}.Rcheck/00check.log
+  - dump_logs
+
+after_failure:
+  - dump_logs
 
 # so no overwrite of linux build
 before_deploy:
+  - if [ "$TRAVIS_OS_NAME" = "osx" ];
+    then
+      PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
+      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
+      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
+      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
+    fi
+  - if [ "$TRAVIS_OS_NAME" = "linux" ];
+    then
+      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1);
+      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
+      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
+      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
+    fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ];
     then
       rm -f *.tar.gz;
@@ -87,4 +163,10 @@ deploy:
     tags: true
 
 after_deploy:
-  - travis_wait 100 Rscript -e 'covr::coveralls(type = "all")'
+  - if [[ "${PACKAGE_NAME}" != "ANTsR" && "${PACKAGE_NAME}" != "ITKR" && "${PACKAGE_NAME}" != "ANTsRCore" ]];
+    then
+      if [[ "${TRAVIS_R_VERSION_STRING}" = "release" ]]; then
+        Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)' ;
+      fi
+    fi
+
